#if !defined(AFX_TEXTTOSPEECH_H__BE058D2E_E938_4C55_B1BD_972A062FD444__INCLUDED_)
#define AFX_TEXTTOSPEECH_H__BE058D2E_E938_4C55_B1BD_972A062FD444__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTextToSpeech wrapper class

//##ModelId=4095FA7A0060
class CTextToSpeech : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTextToSpeech)
public:
	//##ModelId=4095FA7A006E
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2398e32f, 0x5c6e, 0x11d1, { 0x8c, 0x65, 0x0, 0x60, 0x8, 0x18, 0x41, 0xde } };
		return clsid;
	}
	//##ModelId=4095FA7A007D
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

	//##ModelId=4095FA7A00AC
    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	//##ModelId=4095FA7A00DA
	long GetInitialized();
	//##ModelId=4095FA7A00DB
	void SetInitialized(long nNewValue);
	//##ModelId=4095FA7A00EB
	void Speak(LPCTSTR Text);
	//##ModelId=4095FA7A00FB
	void StopSpeaking();
	//##ModelId=4095FA7A0109
	void FastForward();
	//##ModelId=4095FA7A010A
	void Pause();
	//##ModelId=4095FA7A0119
	void Resume();
	//##ModelId=4095FA7A011A
	void Rewind();
	//##ModelId=4095FA7A0128
	long GetDevice();
	//##ModelId=4095FA7A0138
	void SetDevice(long nNewValue);
	//##ModelId=4095FA7A0148
	long GetEnabled();
	//##ModelId=4095FA7A0149
	void SetEnabled(long nNewValue);
	//##ModelId=4095FA7A0158
	long GetIsSpeaking();
	//##ModelId=4095FA7A0167
	long GetSpeed();
	//##ModelId=4095FA7A0177
	void SetSpeed(long nNewValue);
	//##ModelId=4095FA7A0186
	CString GetTTSMode();
	//##ModelId=4095FA7A0187
	void SetTTSMode(LPCTSTR lpszNewValue);
	//##ModelId=4095FA7A0196
	void AboutDlg(long hWnd, LPCTSTR title);
	//##ModelId=4095FA7A01A6
	void GeneralDlg(long hWnd, LPCTSTR title);
	//##ModelId=4095FA7A01B6
	void LexiconDlg(long hWnd, LPCTSTR title);
	//##ModelId=4095FA7A01C6
	void TranslateDlg(long hWnd, LPCTSTR title);
	//##ModelId=4095FA7A01D6
	long GetFindEngine(LPCTSTR EngineId, LPCTSTR MfgName, LPCTSTR ProductName, LPCTSTR ModeID, LPCTSTR ModeName, long LanguageID, LPCTSTR dialect, LPCTSTR Speaker, LPCTSTR Style, long Gender, long Age, long Features, long Interfaces, 
		long EngineFeatures, long RankEngineID, long RankMfgName, long RankProductName, long RankModeID, long RankModeName, long RankLanguage, long RankDialect, long RankSpeaker, long RankStyle, long RankGender, long RankAge, long RankFeatures, 
		long RankInterfaces, long RankEngineFeatures);
	//##ModelId=4095FA7A0262
	long GetCountEngines();
	//##ModelId=4095FA7A0271
	CString ModeName(long index);
	//##ModelId=4095FA7A0273
	CString MfgName(long index);
	//##ModelId=4095FA7A0281
	CString ProductName(long index);
	//##ModelId=4095FA7A0291
	CString ModeID(long index);
	//##ModelId=4095FA7A029F
	CString Speaker(long index);
	//##ModelId=4095FA7A02A1
	CString Style(long index);
	//##ModelId=4095FA7A02B0
	long Gender(long index);
	//##ModelId=4095FA7A02BF
	long Age(long index);
	//##ModelId=4095FA7A02CE
	long Features(long index);
	//##ModelId=4095FA7A02D0
	long Interfaces(long index);
	//##ModelId=4095FA7A02DF
	long EngineFeatures(long index);
	//##ModelId=4095FA7A02EF
	long LanguageID(long index);
	//##ModelId=4095FA7A02FD
	CString dialect(long index);
	//##ModelId=4095FA7A02FF
	short GetMouthHeight();
	//##ModelId=4095FA7A030D
	void SetMouthHeight(short nNewValue);
	//##ModelId=4095FA7A031C
	short GetMouthWidth();
	//##ModelId=4095FA7A031D
	void SetMouthWidth(short nNewValue);
	//##ModelId=4095FA7A032C
	short GetMouthUpturn();
	//##ModelId=4095FA7A032D
	void SetMouthUpturn(short nNewValue);
	//##ModelId=4095FA7A033D
	short GetJawOpen();
	//##ModelId=4095FA7A033E
	void SetJawOpen(short nNewValue);
	//##ModelId=4095FA7A034C
	short GetTeethUpperVisible();
	//##ModelId=4095FA7A034D
	void SetTeethUpperVisible(short nNewValue);
	//##ModelId=4095FA7A035C
	short GetTeethLowerVisible();
	//##ModelId=4095FA7A036B
	void SetTeethLowerVisible(short nNewValue);
	//##ModelId=4095FA7A036D
	short GetTonguePosn();
	//##ModelId=4095FA7A037A
	void SetTonguePosn(short nNewValue);
	//##ModelId=4095FA7A037C
	short GetLipTension();
	//##ModelId=4095FA7A038A
	void SetLipTension(short nNewValue);
	//##ModelId=4095FA7A0399
	long GetLastError();
	//##ModelId=4095FA7A039A
	void SetLastError(long nNewValue);
	//##ModelId=4095FA7A03A9
	short GetSuppressExceptions();
	//##ModelId=4095FA7A03AA
	void SetSuppressExceptions(short nNewValue);
	//##ModelId=4095FA7A03BA
	void Select(long index);
	//##ModelId=4095FA7A03C8
	short GetLipType();
	//##ModelId=4095FA7A03C9
	void SetLipType(short nNewValue);
	//##ModelId=4095FA7B0000
	long GetCurrentMode();
	//##ModelId=4095FA7B0001
	void SetCurrentMode(long nNewValue);
	//##ModelId=4095FA7B0010
	long GetHWnd();
	//##ModelId=4095FA7B0011
	long Find(LPCTSTR RankList);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEXTTOSPEECH_H__BE058D2E_E938_4C55_B1BD_972A062FD444__INCLUDED_)
